GET localhost:18888/
###
POST localhost:18888/api/login HTTP/1.1

{"username": "qza2468", "password": "2468"}

###
POST localhost:18888/api/createuser
token: OIak81AJBwfHiMD6r7gEfOQRli7xWMZue7dm9n5IhiXN2lRtq77UUWvDE28jMhb0

{"username": "bbb", "password": "8888"}

###
POST localhost:18888/api/login HTTP/1.1

{"username": "bbb", "password": "8888"}

###
POST localhost:18888/api/logout
token: E8rXOg0jTAfXCU5aZelTDWyHfm5YSAOhIFEevDMML1uXVz64brVoLU51E8ZgJvNZ

{"tokens_to_delete": ["xHBlALH9M0YEWKgTeAdWA3M7v8xSve0qvBb5XsDrrj5N3loftSB4TV9Oe6rXkrNd", "uKAkgfNYi3qEStmOaUW2EcZGwuTyyg2q0AaeqvCWz0lRuVnUxKUCu2SqwtmsZoiX"]}

###
GET localhost:18888/api/listTokens
all: aaa
token: E8rXOg0jTAfXCU5aZelTDWyHfm5YSAOhIFEevDMML1uXVz64brVoLU51E8ZgJvNZ

###
POST localhost:18888/api/alterUser
token: QHhQVW5k8QqyfRLEUTCqfEMVgNCIx8EMPwmtSrdYFRXuqq9KIJAxXUQDscTnji96

{"username": "aaa", "password": ""}

###
GET localhost:18888/api/listUsers
token: AuFW81MeYKoTmom35VET0WOMmh26sOO2GbXPct18BpbxbMygrC7qhVCTCEX4cv7s

###
POST localhost:18888/api/upload
token: xMbo0RX7VGC4ocyJx3qc4xEPVpyUycGvzrixJF2mTFoGrmZoqOOsJaHpPEJMqXFn
file-path: Li4vLi4vLi4vLi4vYWFhL2NjYy50eHQ=

Hello, World


###
POST localhost:18888/api/rename
token: D3x8LxGVmjZ1rhVEFeDBcfztji0LdxmoyjvKe9nOqNQi4vwHZ8SAnQ3W81pkybWw
file-path: L21tbW1tQXBwLnR4dA==
file-path-new: L0Rvd25sb2Fkcy9tbW1tbUFwcC50eHQ=

###
POST localhost:18888/api/delete
token: WCKs109C4WUMZncFrbPhtBgbuBZxok6LwQByPK8RpalOOLbDwyso7YN1jwwWg2pd
file-path: L0Rvd25sb2Fkcy9tbW1tbUFwcC50eHQ=

###
POST localhost:18888/api/download
token: xMbo0RX7VGC4ocyJx3qc4xEPVpyUycGvzrixJF2mTFoGrmZoqOOsJaHpPEJMqXFn
file-path: Li4vLi4vLi4vLi4vYWFhL2NjY2MudHh0

###
POST localhost:18000/

###
GET 180.76.115.230:18888/api/listdir
token: dIDy2QTBVU7q4GEXLof2qJqlbWEvYEDBWO7YpahK2o863McO8HQzYFk9lz2HDFRh
file-path: Lw==

###
POST localhost:18888/api/mkdir
token: xMbo0RX7VGC4ocyJx3qc4xEPVpyUycGvzrixJF2mTFoGrmZoqOOsJaHpPEJMqXFn
file-path: Li4vLi4vLi4vLi4vfnF6YTI0Njg=

###
POST localhost:18888/api/base64Service/store
token: WSRrRCD5pYKPGgMgVwzoiYFXS5RuqRBMtaBIkNNXthwANGqqDqevMtQmxsfnJq7B
comment-q: cccc89922

fljksadfjkawoipafoiefpaj

###
POST localhost:18888/api/base64Service/listKeys
token: bZbbW531Cv2BLSvEKO7cXkAGb6FwnSsPzUyWZ1VjwXuFznUIAZufH3wt9BnwceJZ

###
POST localhost:18888/api/base64Service/get
token: bZbbW531Cv2BLSvEKO7cXkAGb6FwnSsPzUyWZ1VjwXuFznUIAZufH3wt9BnwceJZ
comment-q: cccc89{}